// Generated by CoffeeScript 1.7.1
(function() {
  var Gogo;

  Gogo = angular.module('Gogo', []);

  this.GogoCtrl = [
    '$scope', '$http', '$location', function($scope, $http, $location) {
      var convertDate, searchFlight;
      convertDate = function(timestamp) {
        var date, day, formattedDate, month, year;
        console.log(timestamp);
        date = new Date(timestamp * 1000);
        day = date.getDay();
        month = date.getMonth();
        year = date.getFullYear();
        formattedDate = "" + month + "/" + day + "/" + year;
        return formattedDate;
      };
      searchFlight = function(airlineNumber) {
        var url;
        url = "http://gogo-test.apigee.net/v1/aircraft/flightno/" + airlineNumber + "?apikey=0XOAphNPi8w4nY1LAqVnhlUIPsBDV69Q";
        return $http.get(url).success(function(data, status, headers, config) {
          return $scope.flight = data.FlightInfo;
        }).error(function(data, status, headers, config) {
          console.log(data);
          console.log(status);
          console.log(headers);
          console.log(config);
          return console.log('error');
        });
      };
      $scope.todos = [
        {
          text: 'learn angular',
          done: true
        }, {
          text: 'build an angular app',
          done: false
        }
      ];
      $scope.viewFlight = function() {
        console.log("Flight");
        return $location.url("/flight");
      };
      $scope.viewNews = function() {
        $location.url("/news");
        return console.log($location.url());
      };
      $scope.viewLeisure = function() {
        $location.url("/leisure");
        return console.log($location.url());
      };
      return $scope.searchFlight = function() {
        return searchFlight($scope.airlineNumberText);
      };
    }
  ];

}).call(this);

//# sourceMappingURL=controller.map
