// Generated by CoffeeScript 1.7.1
(function() {
  var Gogo;

  Gogo = angular.module('Gogo', []);

  this.GogoCtrl = [
    '$scope', '$http', '$location', function($scope, $http, $location) {
      var convertDate, searchFlight, searchNews;
      console.log(angular.isUndefined($scope.flight));
      convertDate = function(timestamp) {
        var date, day, formattedDate, month, year;
        console.log(timestamp);
        date = new Date(timestamp * 1000);
        day = date.getDay();
        month = date.getMonth();
        year = date.getFullYear();
        formattedDate = "" + month + "/" + day + "/" + year;
        return formattedDate;
      };
      searchFlight = function(airlineNumber) {
        var url;
        url = "http://gogo-test.apigee.net/v1/aircraft/flightno/" + airlineNumber + "?apikey=0XOAphNPi8w4nY1LAqVnhlUIPsBDV69Q";
        return $http.get(url).success(function(data, status, headers, config) {
          $scope.flight = data.FlightInfo;
          if (data.FlightInfo.ErrorCode) {
            return $scope.flightSearchSucceed = true;
          } else {
            return $scope.flightSearchSucceed = true;
          }
        }).error(function(data, status, headers, config) {
          return alert('Search failed');
        });
      };
      searchNews = function() {
        var url;
        url = "http://news.google.com/?output=rss";
        return $http.get(url).success(function(data, status, headers, config) {
          var items, newsItems, xml, xmlDoc;
          xmlDoc = $.parseXML(data);
          xml = $(xmlDoc);
          items = xml.find("item");
          newsItems = [];
          items.each(function() {
            var n;
            n = {
              'title': $(this).children().first('title').text(),
              'link': $(this).children().first('link').text()
            };
            return newsItems.push(n);
          });
          return $scope.items = newsItems;
        }).error(function(data, status, headers, config) {
          return console.log('Search Failed');
        });
      };
      searchNews();
      $scope.todos = [
        {
          text: 'learn angular',
          done: true
        }, {
          text: 'build an angular app',
          done: false
        }
      ];
      $scope.viewFlight = function() {
        console.log("Flight");
        return $location.url("/flight");
      };
      $scope.viewNews = function() {
        $location.url("/news");
        return console.log($location.url());
      };
      $scope.viewLeisure = function() {
        $location.url("/leisure");
        return console.log($location.url());
      };
      $scope.searchFlight = function() {
        return searchFlight($scope.airlineNumberText);
      };
      $scope.searchNews = function() {
        return console.log($scope.news);
      };
      $scope.open = function() {
        return chrome.tabs.create({
          url: "http://www.google.com"
        });
      };
      return $scope.flightNotExist = function() {
        return angular.isUndefined($scope.flight);
      };
    }
  ];

}).call(this);

//# sourceMappingURL=controller.map
