// Generated by CoffeeScript 1.7.1
(function() {
  chrome.app.runtime.onLaunched.addListener(function() {
    return chrome.app.window.create('/app/index.html', {
      top: 10,
      width: 500,
      height: 309
    });
  });

}).call(this);

//# sourceMappingURL=main.map
