// Generated by CoffeeScript 1.7.1
(function() {
  chrome.app.runtime.onLaunched.addListener(function() {
    return chrome.app.window.create('/app/index.html', {
      top: 10,
      left: 1100,
      width: 350,
      height: 375
    });
  });

}).call(this);

//# sourceMappingURL=main.map
